name: toDoApp-dev
on: 
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

permissions:
  contents: read

jobs:
  build:
    name: Deploy to develoment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: git checkout
        uses: actions/checkout@v4
      
      - name: Python setup ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install Dependencies [ python code testing, requirements ]
        run: |
          python -m pip install--upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      
      - name: Lint with flake8(for python code test)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      

